### ISSUE TITLE
Binary for empty file

### ISSUE THREAD

**Issue by lorenso** [blackwinter/ruby-filemagic#12]
Hi

For blank text file (ex layout.liquid), method file return "inode/x-empty; charset=binary"

**Comment by blackwinter** [comment]
Please be more specific. What did you do? What did you get? What did you expect?

**Comment by lorenso** [comment]
Created blank text file "layout.liquid" or "readme.txt" or "README"

```
fm = FileMagic.new(FileMagic::MAGIC_MIME)
fm.file('README') # "inode/x-empty; charset=binary"
```

It correct?

**Comment by blackwinter** [comment]
Yes, this is correct. Did you expect something else?

Compare the `file` command:

````sh
$ touch README
$ file -i README
README: inode/x-empty; charset=binary
````

**Comment by lorenso** [comment]
I thought so true `text/plain`

Thank you very much realized his mistake
