### ISSUE TITLE
problem with filename to long error

### ISSUE THREAD

**Issue by NVD-R** [blackwinter/ruby-filemagic#20]
hi,
i get error about filename to long and i search about it but i cant find any thing.can you help me about how can i handled this error?

**
FileMagic::FileMagicError: failed lookup: cannot open 'دریاچه_ی_چیتگر_یا_شهدای_خلیج_فارس_بزرگترین_دریاچه_ی_مصنوعی_ایران_است_که_در_شمال_غرب_شهر_تهران_واقع_شده_و_در_کنار_این_دریاچه_پارک_جنگلی_چیتگر_قرار_گرفته_است.docx' (File name too long)
**

**Comment by blackwinter** [comment]
Can you please provide more information:

* What platform are you on? (`ruby -v`)
* What did you do? (Some code to reproduce the error)
* What version of ruby-filemagic are you using? (`FileMagic::VERSION` and `FileMagic::MAGIC_VERSION`)

**Comment by NVD-R** [comment]
1. ruby 1.9.3p484 (2013-11-22 revision 43786)
2. `def self.verifier
    @ts_verifier ||= ActiveSupport::MessageVerifier.new(TsConfig[:verifier_key])
  end

  def self.text?(filename)
    begin
      fm = FileMagic.new(FileMagic::MAGIC_MIME)
      fm.file(filename) =~ /^text\//
    ensure
      fm.close
    end
  end

  def self.binary?(filename)
    !text?(filename)
  end`
3. 'ruby-filemagic',    '0.7.1'

**Comment by blackwinter** [comment]
I cannot reproduce the error, but I'm almost certain this has nothing to do with ruby-filemagic, anyway. What does `file --mime <your-long-file-name>` say? (Maybe need to install the [file](http://www.darwinsys.com/file/) utility first.)

**Comment by NVD-R** [comment]
file: text/plain; charset=us-ascii

**Comment by blackwinter** [comment]
Can you try `File.open(filename) { |f| fm.fd(f) }` instead of `fm.file(filename)`?

**Comment by NVD-R** [comment]
i use that code but not work !!!
does exist any limitation for filename length in FileMagic?

**Comment by blackwinter** [comment]
> i use that code but not work !!!

Please post the exact error message and backtrace.

> does exist any limitation for filename length in FileMagic?

No, there's not. My suspicion was that `libmagic` had a limit; but seeing as the `file` command worked, we can probably rule that out. Maybe it's Ruby?

* What OS and file system are you running on?
* Which version(s) of libmagic are you using? (`FileMagic::MAGIC_VERSION` and `file -v`)
