### ISSUE TITLE
just can't be installed on OS X

### ISSUE THREAD

**Issue by ivanmarchenko83** [blackwinter/ruby-filemagic#29]
installed
brew install libmagic
but just can't make 
gem install 'ruby-filemagic'
it says ERROR: missing required library to compile this module
the first error in the log file says

ld: library not found for -lgnurx
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and there no nothing like gnurx for OS X

**Comment by blackwinter** [comment]
Can you create a Gist of the mkmf.log file so I can take a look at it? Does the discussion in #13 help?

**Comment by ivanmarchenko83** [comment]
Finally was able to install it by

`env ARCHFLAGS="-arch x86_64" gem install -v 0.7.1 ruby-filemagic -- --with-magic-include=/usr/local/include --with-magic-lib=/usr/local/lib/`

please post it in OS X install section - spent a lot of time on this one.
Thanks.
